import type { ProductCategory, ProductType, TargetSurface } from "@/lib/room-preview/types";

export type QrProductManifestEntry = {
  code: string;
  category: ProductCategory;
  targetSurface: TargetSurface;
  productType: ProductType;
  imageUrl: string;
};

// Generated by scripts/generate-qr-product-manifest.mjs.
// Runtime code must read this lightweight manifest instead of scanning public/qr-products.
export const QR_PRODUCT_MANIFEST = [
  {"code":"PQC201.132","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.132.jpg"},
  {"code":"PQC201.133","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.133.jpg"},
  {"code":"PQC201.134","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.134.jpg"},
  {"code":"PQC201.135","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.135.jpg"},
  {"code":"PQH111.151","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.151.jpg"},
  {"code":"PQH111.152","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.152.jpg"},
  {"code":"PQH111.154","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.154.jpg"},
  {"code":"WPT01-1101-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01-1101-1.jpg"},
  {"code":"WPT01.1101-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1101-5.jpg"},
  {"code":"WPT01.1104-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1104-1.jpg"},
  {"code":"WPT01.1107-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1107-5.jpg"},
  {"code":"WPT01.1108-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1108-1.jpg"},
  {"code":"WPT01.1108-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1108-4.jpg"},
  {"code":"WPT01.1109-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1109-1.jpg"},
  {"code":"WPT01.1109-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1109-2.jpg"},
  {"code":"WPT01.1110-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-2.jpg"},
  {"code":"WPT01.1110-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-3.jpg"},
  {"code":"WPT01.1110-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-5.jpg"},
  {"code":"WPT01.1112-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-1.jpg"},
  {"code":"WPT01.1112-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-4.jpg"},
  {"code":"WPT01.1112-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-5.jpg"},
  {"code":"WPT01.1112-7","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-7.jpg"},
  {"code":"WPT01.1112-8","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-8.jpg"},
  {"code":"WPT01.1113-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-1.jpg"},
  {"code":"WPT01.1113-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-2.jpg"},
  {"code":"WPT01.1113-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-3.jpg"},
  {"code":"WPT01.1113-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-4.jpg"},
  {"code":"WPT01.1113-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-5.jpg"},
  {"code":"WPT01.1113-6","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-6.jpg"},
  {"code":"WPT01.1501-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1501-1.jpg"},
  {"code":"WPT01.1501-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1501-3.jpg"},
  {"code":"WPT01.1503-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1503-1.jpg"},
  {"code":"WPT01.1503-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1503-2.jpg"},
  {"code":"WPT01.1504-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1504-1.jpg"},
  {"code":"WPT01.1504-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1504-2.jpg"},
  {"code":"WPT01.1507-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-1.jpg"},
  {"code":"WPT01.1507-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-3.jpg"},
  {"code":"WPT01.1507-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-5.jpg"},
  {"code":"WPT01.1514-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1514-3.jpg"},
  {"code":"WPT01.23101-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23101-1.jpg"},
  {"code":"WPT01.23101-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23101-2.jpg"},
  {"code":"WPT01.23102-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23102-1.jpg"},
  {"code":"WPT01.23104-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23104-3.jpg"},
  {"code":"WPT01.23106-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23106-5.jpg"},
  {"code":"WPT01.23107-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23107-5.jpg"},
  {"code":"WPT01.23111-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23111-3.jpg"},
  {"code":"WPT01.23204-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23204-1.jpg"},
  {"code":"WPT01.23210-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23210-1.jpg"},
  {"code":"WPT01.23210-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23210-3.jpg"},
  {"code":"WPT01.23211-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23211-2.jpg"},
  {"code":"WPT01.23211-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23211-3.jpg"},
  {"code":"WPT01.23212-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23212-2.jpg"},
  {"code":"WPT01.23213-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23213-1.jpg"},
  {"code":"WPT01.23213-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23213-2.jpg"},
] as const satisfies readonly QrProductManifestEntry[];

