import type { ProductCategory, ProductType, TargetSurface } from "@/lib/room-preview/types";

export type QrProductManifestEntry = {
  code: string;
  category: ProductCategory;
  targetSurface: TargetSurface;
  productType: ProductType;
  imageUrl: string;
};

// Generated by scripts/generate-qr-product-manifest.mjs.
// Runtime code must read this lightweight manifest instead of scanning public/qr-products.
export const QR_PRODUCT_MANIFEST = [
  {"code":"PQC201.132","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.132.jpg"},
  {"code":"PQC201.133","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.133.jpg"},
  {"code":"PQC201.134","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.134.jpg"},
  {"code":"PQC201.135","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQC201.135.jpg"},
  {"code":"PQH111.151","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.151.jpg"},
  {"code":"PQH111.152","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.152.jpg"},
  {"code":"PQH111.154","category":"PARQUET","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/parquet/PQH111.154.jpg"},
  {"code":"WPT01-1101-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01-1101-1.jpg"},
  {"code":"WPT01.1101-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1101-5.jpg"},
  {"code":"WPT01.1104-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1104-1.jpg"},
  {"code":"WPT01.1107-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1107-5.jpg"},
  {"code":"WPT01.1108-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1108-1.jpg"},
  {"code":"WPT01.1108-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1108-4.jpg"},
  {"code":"WPT01.1109-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1109-1.jpg"},
  {"code":"WPT01.1109-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1109-2.jpg"},
  {"code":"WPT01.1110-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-2.jpg"},
  {"code":"WPT01.1110-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-3.jpg"},
  {"code":"WPT01.1110-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1110-5.jpg"},
  {"code":"WPT01.1112-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-1.jpg"},
  {"code":"WPT01.1112-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-4.jpg"},
  {"code":"WPT01.1112-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-5.jpg"},
  {"code":"WPT01.1112-7","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-7.jpg"},
  {"code":"WPT01.1112-8","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1112-8.jpg"},
  {"code":"WPT01.1113-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-1.jpg"},
  {"code":"WPT01.1113-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-2.jpg"},
  {"code":"WPT01.1113-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-3.jpg"},
  {"code":"WPT01.1113-4","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-4.jpg"},
  {"code":"WPT01.1113-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-5.jpg"},
  {"code":"WPT01.1113-6","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1113-6.jpg"},
  {"code":"WPT01.1501-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1501-1.jpg"},
  {"code":"WPT01.1501-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1501-3.jpg"},
  {"code":"WPT01.1503-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1503-1.jpg"},
  {"code":"WPT01.1503-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1503-2.jpg"},
  {"code":"WPT01.1504-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1504-1.jpg"},
  {"code":"WPT01.1504-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1504-2.jpg"},
  {"code":"WPT01.1507-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-1.jpg"},
  {"code":"WPT01.1507-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-3.jpg"},
  {"code":"WPT01.1507-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1507-5.jpg"},
  {"code":"WPT01.1514-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.1514-3.jpg"},
  {"code":"WPT01.23101-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23101-1.jpg"},
  {"code":"WPT01.23101-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23101-2.jpg"},
  {"code":"WPT01.23102-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23102-1.jpg"},
  {"code":"WPT01.23104-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23104-3.jpg"},
  {"code":"WPT01.23106-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23106-5.jpg"},
  {"code":"WPT01.23107-5","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23107-5.jpg"},
  {"code":"WPT01.23111-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23111-3.jpg"},
  {"code":"WPT01.23204-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23204-1.jpg"},
  {"code":"WPT01.23210-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23210-1.jpg"},
  {"code":"WPT01.23210-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23210-3.jpg"},
  {"code":"WPT01.23211-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23211-2.jpg"},
  {"code":"WPT01.23211-3","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23211-3.jpg"},
  {"code":"WPT01.23212-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23212-2.jpg"},
  {"code":"WPT01.23213-1","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23213-1.jpg"},
  {"code":"WPT01.23213-2","category":"WALLPAPER","targetSurface":"walls","productType":"wall_material","imageUrl":"/qr-products/wallpaper/WPT01.23213-2.jpg"},

  // Carpet tile (CRP) SKUs — manually added, NOT scanned from a local image
  // folder by the generator script (no bundled carpet-tile images exist).
  // /qr-print and the render flow both resolve name + image from PDC via
  // resolveProductByCode(); this imageUrl is only ever read as the
  // development-only PDC-outage fallback in product-resolver.ts and is never
  // shown in production.
  {"code":"CRPT050.001","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.001.jpg"},
  {"code":"CRPT050.006","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.006.jpg"},
  {"code":"CRPT050.007","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.007.jpg"},
  {"code":"CRPT050.009","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.009.jpg"},
  {"code":"CRPT050.051","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.051.jpg"},
  {"code":"CRPT050.056","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.056.jpg"},
  {"code":"CRPT050.057","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.057.jpg"},
  {"code":"CRPT050.058","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT050.058.jpg"},
  {"code":"CRPT060.001","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.001.jpg"},
  {"code":"CRPT060.002","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.002.jpg"},
  {"code":"CRPT060.004","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.004.jpg"},
  {"code":"CRPT060.006","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.006.jpg"},
  {"code":"CRPT060.007","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.007.jpg"},
  {"code":"CRPT060.008","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.008.jpg"},
  {"code":"CRPT060.010","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.010.jpg"},
  {"code":"CRPT060.011","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.011.jpg"},
  {"code":"CRPT060.015","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.015.jpg"},
  {"code":"CRPT060.018","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.018.jpg"},
  {"code":"CRPT060.025","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.025.jpg"},
  {"code":"CRPT060.026","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.026.jpg"},
  {"code":"CRPT060.027","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.027.jpg"},
  {"code":"CRPT060.061","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.061.jpg"},
  {"code":"CRPT060.062","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.062.jpg"},
  {"code":"CRPT060.063","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.063.jpg"},
  {"code":"CRPT060.100","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.100.jpg"},
  {"code":"CRPT060.105","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.105.jpg"},
  {"code":"CRPT060.202","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.202.jpg"},
  {"code":"CRPT060.203","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.203.jpg"},
  {"code":"CRPT060.204","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.204.jpg"},
  {"code":"CRPT060.303","category":"CARPET_TILE","targetSurface":"floor","productType":"floor_material","imageUrl":"/qr-products/carpet-tile/CRPT060.303.jpg"},
] as const satisfies readonly QrProductManifestEntry[];

